/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolRouteImport } from './routes/tool'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiDetectRouteImport } from './routes/api/detect'
import { Route as ApiConvertRouteImport } from './routes/api/convert'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const ToolRoute = ToolRouteImport.update({
  id: '/tool',
  path: '/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDetectRoute = ApiDetectRouteImport.update({
  id: '/api/detect',
  path: '/api/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConvertRoute = ApiConvertRouteImport.update({
  id: '/api/convert',
  path: '/api/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tool': typeof ToolRoute
  '/api/chat': typeof ApiChatRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/detect': typeof ApiDetectRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tool': typeof ToolRoute
  '/api/chat': typeof ApiChatRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/detect': typeof ApiDetectRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tool': typeof ToolRoute
  '/api/chat': typeof ApiChatRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/detect': typeof ApiDetectRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/tool'
    | '/api/chat'
    | '/api/convert'
    | '/api/detect'
    | '/api/download'
    | '/api/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/tool'
    | '/api/chat'
    | '/api/convert'
    | '/api/detect'
    | '/api/download'
    | '/api/health'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/tool'
    | '/api/chat'
    | '/api/convert'
    | '/api/detect'
    | '/api/download'
    | '/api/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ToolRoute: typeof ToolRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConvertRoute: typeof ApiConvertRoute
  ApiDetectRoute: typeof ApiDetectRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tool': {
      id: '/tool'
      path: '/tool'
      fullPath: '/tool'
      preLoaderRoute: typeof ToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/detect': {
      id: '/api/detect'
      path: '/api/detect'
      fullPath: '/api/detect'
      preLoaderRoute: typeof ApiDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/convert': {
      id: '/api/convert'
      path: '/api/convert'
      fullPath: '/api/convert'
      preLoaderRoute: typeof ApiConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ToolRoute: ToolRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConvertRoute: ApiConvertRoute,
  ApiDetectRoute: ApiDetectRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
