/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolRouteImport } from './routes/tool'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiProxySettingsRouteImport } from './routes/api/proxy/settings'
import { Route as ApiProxyHealthRouteImport } from './routes/api/proxy/health'
import { Route as ApiProxyDownloadRouteImport } from './routes/api/proxy/download'
import { Route as ApiProxyDetectRouteImport } from './routes/api/proxy/detect'
import { Route as ApiProxyConvertRouteImport } from './routes/api/proxy/convert'

const ToolRoute = ToolRouteImport.update({
  id: '/tool',
  path: '/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySettingsRoute = ApiProxySettingsRouteImport.update({
  id: '/api/proxy/settings',
  path: '/api/proxy/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyHealthRoute = ApiProxyHealthRouteImport.update({
  id: '/api/proxy/health',
  path: '/api/proxy/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyDownloadRoute = ApiProxyDownloadRouteImport.update({
  id: '/api/proxy/download',
  path: '/api/proxy/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyDetectRoute = ApiProxyDetectRouteImport.update({
  id: '/api/proxy/detect',
  path: '/api/proxy/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyConvertRoute = ApiProxyConvertRouteImport.update({
  id: '/api/proxy/convert',
  path: '/api/proxy/convert',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deploy': typeof DeployRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tool': typeof ToolRoute
  '/api/chat': typeof ApiChatRoute
  '/api/proxy/convert': typeof ApiProxyConvertRoute
  '/api/proxy/detect': typeof ApiProxyDetectRoute
  '/api/proxy/download': typeof ApiProxyDownloadRoute
  '/api/proxy/health': typeof ApiProxyHealthRoute
  '/api/proxy/settings': typeof ApiProxySettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deploy': typeof DeployRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tool': typeof ToolRoute
  '/api/chat': typeof ApiChatRoute
  '/api/proxy/convert': typeof ApiProxyConvertRoute
  '/api/proxy/detect': typeof ApiProxyDetectRoute
  '/api/proxy/download': typeof ApiProxyDownloadRoute
  '/api/proxy/health': typeof ApiProxyHealthRoute
  '/api/proxy/settings': typeof ApiProxySettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deploy': typeof DeployRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tool': typeof ToolRoute
  '/api/chat': typeof ApiChatRoute
  '/api/proxy/convert': typeof ApiProxyConvertRoute
  '/api/proxy/detect': typeof ApiProxyDetectRoute
  '/api/proxy/download': typeof ApiProxyDownloadRoute
  '/api/proxy/health': typeof ApiProxyHealthRoute
  '/api/proxy/settings': typeof ApiProxySettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deploy'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/privacy'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/tool'
    | '/api/chat'
    | '/api/proxy/convert'
    | '/api/proxy/detect'
    | '/api/proxy/download'
    | '/api/proxy/health'
    | '/api/proxy/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deploy'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/privacy'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/tool'
    | '/api/chat'
    | '/api/proxy/convert'
    | '/api/proxy/detect'
    | '/api/proxy/download'
    | '/api/proxy/health'
    | '/api/proxy/settings'
  id:
    | '__root__'
    | '/'
    | '/deploy'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/privacy'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/tool'
    | '/api/chat'
    | '/api/proxy/convert'
    | '/api/proxy/detect'
    | '/api/proxy/download'
    | '/api/proxy/health'
    | '/api/proxy/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeployRoute: typeof DeployRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolRoute: typeof ToolRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiProxyConvertRoute: typeof ApiProxyConvertRoute
  ApiProxyDetectRoute: typeof ApiProxyDetectRoute
  ApiProxyDownloadRoute: typeof ApiProxyDownloadRoute
  ApiProxyHealthRoute: typeof ApiProxyHealthRoute
  ApiProxySettingsRoute: typeof ApiProxySettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tool': {
      id: '/tool'
      path: '/tool'
      fullPath: '/tool'
      preLoaderRoute: typeof ToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/settings': {
      id: '/api/proxy/settings'
      path: '/api/proxy/settings'
      fullPath: '/api/proxy/settings'
      preLoaderRoute: typeof ApiProxySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/health': {
      id: '/api/proxy/health'
      path: '/api/proxy/health'
      fullPath: '/api/proxy/health'
      preLoaderRoute: typeof ApiProxyHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/download': {
      id: '/api/proxy/download'
      path: '/api/proxy/download'
      fullPath: '/api/proxy/download'
      preLoaderRoute: typeof ApiProxyDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/detect': {
      id: '/api/proxy/detect'
      path: '/api/proxy/detect'
      fullPath: '/api/proxy/detect'
      preLoaderRoute: typeof ApiProxyDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/convert': {
      id: '/api/proxy/convert'
      path: '/api/proxy/convert'
      fullPath: '/api/proxy/convert'
      preLoaderRoute: typeof ApiProxyConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeployRoute: DeployRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolRoute: ToolRoute,
  ApiChatRoute: ApiChatRoute,
  ApiProxyConvertRoute: ApiProxyConvertRoute,
  ApiProxyDetectRoute: ApiProxyDetectRoute,
  ApiProxyDownloadRoute: ApiProxyDownloadRoute,
  ApiProxyHealthRoute: ApiProxyHealthRoute,
  ApiProxySettingsRoute: ApiProxySettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
